# -*- coding: utf-8 -*-
"""S3 Load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151VGRlo0rySLSdazynDg--ZzHaRMHjgD
"""

# Personal AWS credentials
AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_REGION = 'us-east-1'
bucket_name = "ecommercelogistics"

# S3 resource setup
s3_files = boto3.resource(
    service_name='s3',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_REGION
)

s3_files.create_bucket(Bucket=bucket_name)
print("Objects in S3 bucket:")

bucket = s3_files.Bucket(bucket_name)

for obj in bucket.objects.all():
    print(obj.key)

!aws configure

